project:
  type: website
  output-dir: docs
execute: 
  freeze: auto

website:
  title: "HPPU now as a site for technical documentation"
  site-url: "https://impact-initiatives-hppu.github.io/""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



